# Sales data

# Importing datframes & Viewing information

In [1]:
import pandas as pd
excel_file = pd.ExcelFile("Regional Sales Dataset.xlsx")
print(excel_file.sheet_names)

['Sales Orders', 'Customers', 'Regions', 'State Regions', 'Products', '2017 Budgets']

In [2]:
sales_orders = pd.read_excel("Regional Sales Dataset.xlsx", sheet_name = "Sales Orders")
customers = pd.read_excel("Regional Sales Dataset.xlsx", sheet_name = "Customers")
regions = pd.read_excel("Regional Sales Dataset.xlsx", sheet_name = "Regions")
products = pd.read_excel("Regional Sales Dataset.xlsx", sheet_name = "Products")
state_reg = pd.read_excel("Regional Sales Dataset.xlsx", sheet_name = "State Regions")
# budgets = pd.read_excel("Regional Sales Dataset.xlsx", sheet_name = "2017 Budgets")

In [3]:
sales_orders['OrderDate'] = pd.to_datetime({'year': sales_orders['OrderDate'].dt.year + 8, 'month': sales_orders['OrderDate'].dt.month, 'day': sales_orders['OrderDate'].dt.day})

In [4]:
products.head()

   Index                     Product Name     Category
0      1             Dell Business Laptop  IT Hardware
1      2             Business Monitor 24"  IT Hardware
2      3            USB-C Docking Station  IT Hardware
3      4  Wireless Keyboard & Mouse Combo  IT Hardware
4      5        Enterprise Network Switch  IT Hardware

In [5]:
sales_orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64104 entries, 0 to 64103
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   OrderNumber                64104 non-null  object
 1   OrderDate                  64104 non-null  datetime64[ns]
 2   Customer Name Index        64104 non-null  int64
 3   Channel                    64104 non-null  object
 4   Currency Code              64104 non-null  object
 5   Warehouse Code             64104 non-null  object
 6   Delivery Region Index      64104 non-null  int64
 7   Product Description Index  64104 non-null  int64
 8   Order Quantity             64104 non-null  int64
 9   Unit Price                 64104 non-null  float64
 10  Line Total                 64104 non-null  float64
 11  Total Unit Cost            64104 non-null  float64
dtypes: datetime64[ns](1), float64(3), int64(4), object(4)
memory usage: 5.9+ MB

In [6]:
#print('sales_orders.head():\n', sales_orders.head(), '\n')
print('customers.head():\n', customers.head(), '\n')
print('regions.head():\n', regions.head(), '\n')
print('products.head():\n', products.head(), '\n')
print('state_reg.head():\n', state_reg.head(), '\n')
# print('budgets.head():\n', budgets.head(), '\n')

customers.head():
    Customer Index Customer Names
0               1  Geiss Company
1               2  Jaxbean Group
2               3     Ascend Ltd
3               4      Eire Corp
4               5   Blogtags Ltd

regions.head():
    id        name                                   county state_code  \
0   1      Auburn                               Lee County         AL
1   2  Birmingham           Shelby County/Jefferson County         AL
2   3     Decatur           Limestone County/Morgan County         AL
3   4      Dothan  Dale County/Houston County/Henry County         AL
4   5      Hoover           Shelby County/Jefferson County         AL

     state  type  latitude  longitude  area_code  population  households  \
0  Alabama  City  32.60986  -85.48078        334       62059       21767
1  Alabama  City  33.52744  -86.79905        205      212461       89972
2  Alabama  City  34.57332  -86.99214        256       55437       22294
3  Alabama  City  31.23370  -85.40682        334       68567       25913
4  Alabama  City  33.37695  -86.80558        205       84848       32789

   median_income  land_area  water_area        time_zone
0          38342  152375113     2646161  America/Chicago
1          31061  378353942     6591013  America/Chicago
2          41496  141006257    17594716  America/Chicago
3          42426  232166237      835468  America/Chicago
4          77146  122016784     2553332  America/Chicago

products.head():
    Index                     Product Name     Category
0      1             Dell Business Laptop  IT Hardware
1      2             Business Monitor 24"  IT Hardware
2      3            USB-C Docking Station  IT Hardware
3      4  Wireless Keyboard & Mouse Combo  IT Hardware
4      5        Enterprise Network Switch  IT Hardware

state_reg.head():
       Column1     Column2 Column3
0  State Code       State  Region
1          AL     Alabama   South
2          AR    Arkansas   South
3          AZ     Arizona    West
4          CA  California    West

# Cleaning 
(Null/Duplicate check, remove unneccessary columns, rename cols.)

In [7]:
new_header = state_reg.iloc[0]
state_reg.columns = new_header
state_reg = state_reg[1:]

state_reg.head()

0 State Code       State Region
1         AL     Alabama  South
2         AR    Arkansas  South
3         AZ     Arizona   West
4         CA  California   West
5         CO    Colorado   West

Null check

In [8]:
print('Missing values in sales_orders:\n', sales_orders.isnull().sum(), '\n')
print('Missing values in customers:\n', customers.isnull().sum(), '\n')
print('Missing values in regions:\n', regions.isnull().sum(), '\n')
print('Missing values in products:\n', products.isnull().sum(), '\n')
print('Missing values in state_reg:\n', state_reg.isnull().sum(), '\n')
#print('Missing values in budgets:\n', budgets.isnull().sum(), '\n')

Missing values in sales_orders:
 OrderNumber                  0
OrderDate                    0
Customer Name Index          0
Channel                      0
Currency Code                0
Warehouse Code               0
Delivery Region Index        0
Product Description Index    0
Order Quantity               0
Unit Price                   0
Line Total                   0
Total Unit Cost              0
dtype: int64

Missing values in customers:
 Customer Index    0
Customer Names    0
dtype: int64

Missing values in regions:
 id               0
name             0
county           0
state_code       0
state            0
type             0
latitude         0
longitude        0
area_code        0
population       0
households       0
median_income    0
land_area        0
water_area       0
time_zone        0
dtype: int64

Missing values in products:
 Index           0
Product Name    0
Category        0
dtype: int64

Missing values in state_reg:
 0
State Code    0
State         0
Region        0
dtype: int64

NameError: name 'budgets' is not defined

In [10]:
df = sales_orders.merge(customers,how = 'left',left_on = 'Customer Name Index', right_on='Customer Index')
df = df.merge(products,how = 'left',left_on = 'Product Description Index', right_on='Index')
df = df.merge(regions,how = 'left',left_on = 'Delivery Region Index', right_on='id')
df = df.merge(state_reg[['State Code', 'Region']],how = 'left',left_on = 'state_code', right_on='State Code')
# df = df.merge(budgets,how = 'left',left_on = 'Delivery Region Index', right_on='Region')

In [ ]:
df.head()

In [11]:
df.columns

Index(['OrderNumber', 'OrderDate', 'Customer Name Index', 'Channel',
       'Currency Code', 'Warehouse Code', 'Delivery Region Index',
       'Product Description Index', 'Order Quantity', 'Unit Price',
       'Line Total', 'Total Unit Cost', 'Customer Index', 'Customer Names',
       'Index', 'Product Name', 'Category', 'id', 'name', 'county',
       'state_code', 'state', 'type', 'latitude', 'longitude', 'area_code',
       'population', 'households', 'median_income', 'land_area', 'water_area',
       'time_zone', 'State Code', 'Region'],
      dtype='object')

In [12]:
df.drop(columns=['Customer Name Index', 'Index', 'id','state_code'], axis=1, inplace=True)

In [ ]:
# Remove irrelevant columns (take any one down or this)
df.drop(columns=['Product Description Index','Customer Index', 'Currency Code', 'type','households', 'State Code'], axis=1, inplace=True)

In [13]:
df.drop(columns=['latitude', 'longitude', 'area_code','land_area', 'water_area', 'time_zone'], axis=1, inplace=True)

In [14]:
df.columns

Index(['OrderNumber', 'OrderDate', 'Channel', 'Currency Code',
       'Warehouse Code', 'Delivery Region Index', 'Product Description Index',
       'Order Quantity', 'Unit Price', 'Line Total', 'Total Unit Cost',
       'Customer Index', 'Customer Names', 'Product Name', 'Category', 'name',
       'county', 'state', 'type', 'population', 'households', 'median_income',
       'State Code', 'Region'],
      dtype='object')

In [15]:
df = df[['OrderNumber', 'OrderDate','Channel',
       'Product Name','Category', 'Order Quantity', 'Unit Price',
       'Line Total', 'Total Unit Cost', 'Customer Names','Delivery Region Index', 'name', 'county', 'state',
       'population', 'median_income',
       'Region','Warehouse Code']]

In [16]:
print(len(df.columns))

18

In [17]:
df.columns = df.columns.str.lower()

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64104 entries, 0 to 64103
Data columns (total 18 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   ordernumber            64104 non-null  object
 1   orderdate              64104 non-null  datetime64[ns]
 2   channel                64104 non-null  object
 3   product name           64104 non-null  object
 4   category               64104 non-null  object
 5   order quantity         64104 non-null  int64
 6   unit price             64104 non-null  float64
 7   line total             64104 non-null  float64
 8   total unit cost        64104 non-null  float64
 9   customer names         64104 non-null  object
 10  delivery region index  64104 non-null  int64
 11  name                   64104 non-null  object
 12  county                 64104 non-null  object
 13  state                  64104 non-null  object
 14  population             64104 non-null  int64
 15  median_income          64104 non-null  int64
 16  region                 64104 non-null  object
 17  warehouse code         64104 non-null  object
dtypes: datetime64[ns](1), float64(3), int64(4), object(10)
memory usage: 8.8+ MB

In [19]:
# Change column name
df.rename(columns={'product name': 'product_name',
                   'order quantity': 'order_quantity',
                   'unit price': 'unit_price(USD)',
                   'line total': 'revenue(USD)',
                   'total unit cost': 'mfg_cost(USD)',
                   'customer names': 'customer_name',
                   'delivery region index': 'delivery_region_index',
                   'name': 'region_name',
                   'population': 'population',
                   'median income': 'median_income(USD)',
                   'warehouse code': 'warehouse_code'
                   }, inplace=True)

In [ ]:
df.head()

# Featue Engineering

In [20]:
# Important Features
df['total_mfg_cost'] = df['mfg_cost(USD)'] * df['order_quantity']
df['profit'] = df['revenue(USD)'] - df['total_mfg_cost']
df['profit_margin(%)'] = (df['profit'] / df['revenue(USD)'])*100

**Column to show gap between purchases**

In [21]:
df = df.sort_values(['customer_name', 'orderdate'])

In [22]:
df['Previous_Purchase_Date'] = (
    df.groupby('customer_name')['orderdate']
      .shift(1)
)

In [23]:
df['Gap_Days'] = (
    df['orderdate'] - df['Previous_Purchase_Date']
).dt.days

In [24]:
df.head()

,ordernumber,orderdate,channel,product_name,category,order_quantity,unit_price(USD),revenue(USD),mfg_cost(USD),customer_name,...,state,population,median_income,region,warehouse_code,total_mfg_cost,profit,profit_margin(%),Previous_Purchase_Date,Gap_Days
44,SO - 0004126,2022-01-02,Wholesale,Paper Towel Roll,Facility Supplies,10,3041.8,30418.0,2038.006,ALK-Abello Ltd,...,Florida,51617,41494,South,AXW291,20380.060,10037.940,33.0,NaT,NaN
179,SO - 0007533,2022-01-04,Wholesale,Wireless Keyboard & Mouse Combo,IT Hardware,6,2371.8,14230.8,1209.618,ALK-Abello Ltd,...,Washington,60598,103409,West,AXW291,7257.708,6973.092,49.0,2022-01-02,2.0
196,SO - 0004669,2022-01-05,Distributor,Ball Bearing,Industrial Consumables,10,6210.9,62109.0,2857.014,ALK-Abello Ltd,...,Indiana,71111,40419,Midwest,GUT930,28570.140,33538.860,54.0,2022-01-04,1.0
224,SO - 0005440,2022-01-05,Distributor,Enterprise Network Switch,IT Hardware,11,917.9,10096.9,706.783,ALK-Abello Ltd,...,Missouri,166810,33557,Midwest,GUT930,7774.613,2322.287,23.0,2022-01-05,0.0
247,SO - 0004230,2022-01-06,Export,"Business Monitor 24""",IT Hardware,12,1889.4,22672.8,888.018,ALK-Abello Ltd,...,California,864816,81294,West,AXW291,10656.216,12016.584,53.0,2022-01-05,1.0

In [35]:
customer_summary = (
    df.groupby('customer_name')
      .agg(
          Total_Orders=('orderdate', 'count'),
          Avg_Gap_Days=('Gap_Days', 'mean'),
          Min_Gap=('Gap_Days', 'min'),
          Max_Gap=('Gap_Days', 'max')
      )
      .reset_index()
)

In [40]:
print(type(customer_summary))

<class 'pandas.core.frame.DataFrame'>

In [39]:
x = customer_summary['Avg_Gap_Days'].mean().round(2)
print(x)

4.24

In [36]:
print(customer_summary)

        customer_name  Total_Orders  Avg_Gap_Days  Min_Gap  Max_Gap
0      ALK-Abello Ltd           402      3.775561      0.0     29.0
1        Accord Group           330      4.568389      0.0     23.0
2    Accudial Company           366      4.145205      0.0     27.0
3     Actavis Company           378      4.029178      0.0     30.0
4       Aibox Company           516      2.933981      0.0     17.0
..                ...           ...           ...      ...      ...
170     Zoonoodle Ltd           366      4.156164      0.0     20.0
171    Zooveo Company           390      3.904884      0.0     23.0
172        Zoovu Corp           312      4.868167      0.0     28.0
173         Zooxo Ltd           366      4.158904      0.0     32.0
174  sanofi-ave Group           312      4.877814      0.0     22.0

[175 rows x 5 columns]

# Exporting data
Connecting to postgreSQL

In [ ]:
df.to_csv("Sales_cleaned")

In [ ]:
pip install psycopg

In [ ]:
from sqlalchemy import create_engine

In [ ]:
username = "postgres"
password = "2006"
host = "localhost"
port = "5432"
database = "Regional sales"

engine = create_engine(
    f"postgresql+psycopg://{username}:{password}@{host}:{port}/{database}"
)

In [ ]:
df.to_sql(
    name="sales",      # Table name in PostgreSQL
    con=engine,
    if_exists="replace",  
    index=False
)

In [ ]:
df_check = pd.read_sql("SELECT * FROM Sales data;", engine)
df_check.head()